# Generated by Django 2.1.4 on 2019-01-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
